#!/bin/bash
touch passwordfile.txt
truncate -s 0 passwordfile.txt
echo "email">>passwordfile.txt
echo "password$1" >> passwordfile.txt
sudo openvpn --config vpnconfigfile_path --auth-user-pass passwordfile.txt

